# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ebcd40acd82958e9abd87d442654e9e55e9bcaf320d515d73e66d519fd314298bf4466fd1ff2a0ac62896fa9a515ed3d86ae7b0415c6ece5605fb2e9a362efa6

test:
  secret_key_base: 5ce366cae90dc7ab83422c722675de8ae784d30149f30d38f40d170bd908e68b48a616dc98e1659fd687232347734f9c7df44a78d7326d54491227e0f1959cbb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
